# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userimport', '0003_auto_20160421_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users'},
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
