# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userimport', '0004_auto_20160421_1105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
