# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userimport', '0007_auto_20160421_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
