# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userimport', '0008_auto_20160421_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
