# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userimport', '0009_auto_20160421_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
    ]
